version: '3.8'

services:
  bluepulse-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:bluepulse123@db:5432/bluepulse_ml
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bluepulse_ml
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bluepulse123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - bluepulse-web
    restart: unless-stopped

volumes:
  postgres_data: